### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by siyuan126** [SeunOlowo7/pwp-capstones#1]
**Overall Score: 14/16**
Overall great job! Here is the breakdown.

**Criteria 1: Valid Python Code**
Score Level: 3 (meets expectations)
Comment(s): Code included runs without any errors. (object) are missing when define Class Book and Class TomeRater. 

**Criteria 2: Implementation of Project Requirements**
Score Level: 4 (exceeds expectations)
Comment(s): Code produces the suite of functions and classes required of it and calls them in an appropriate order. But I do recommend to put functions repr, eq, hash at the end of the class to increase readability.

**Criteria 3: Software Architecture**
Score Level: 4 (exceeds expectations)
Comment(s): Code is separated into distinct classes and functions each which are invoked for their own purposes.

**Criteria 4: Uses Python Language Features**
Score Level: 3 (Meets expectations)
Comment(s): Code uses language features appropriately. If a task can be solved with a Python language feature, it is. Triple quotes are used around muti-line text, single line text is wrapped inside single quotes (line 152).

**Comment by SeunOlowo7** [comment]
Noted! Thanks for the feedback @siyuan126 .

**Comment by SeunOlowo7** [comment]
I will close this issues. Please let me know if there are other issues.
